# Generated by Django 3.2 on 2022-01-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_banking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
