# Generated by Django 3.2 on 2022-01-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_banking', '0002_remove_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
